// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXAtquIzyVXjiIUoabjCENsSwqQzp_Tw4',
    appId: '1:756950731526:web:a1b193142043f69407ec87',
    messagingSenderId: '756950731526',
    projectId: 'dream-job-5a696',
    authDomain: 'dream-job-5a696.firebaseapp.com',
    storageBucket: 'dream-job-5a696.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Gm0s4uiwEjDVE-WsKPKEo24l8Q98F10',
    appId: '1:756950731526:android:a3f94b9259b0bd0407ec87',
    messagingSenderId: '756950731526',
    projectId: 'dream-job-5a696',
    storageBucket: 'dream-job-5a696.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVzdp8dXxIHkmYG3JN3AqdiVHNBxXxbRw',
    appId: '1:756950731526:ios:67f7fb79f5e1786e07ec87',
    messagingSenderId: '756950731526',
    projectId: 'dream-job-5a696',
    storageBucket: 'dream-job-5a696.appspot.com',
    iosClientId: '756950731526-s7di3prclfplmlm9a93olalhsmp5ecv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamjob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVzdp8dXxIHkmYG3JN3AqdiVHNBxXxbRw',
    appId: '1:756950731526:ios:67f7fb79f5e1786e07ec87',
    messagingSenderId: '756950731526',
    projectId: 'dream-job-5a696',
    storageBucket: 'dream-job-5a696.appspot.com',
    iosClientId: '756950731526-s7di3prclfplmlm9a93olalhsmp5ecv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamjob',
  );
}
